#!/bin/bash
# Runs on the HOST before the container is created.
# Detects GPU availability and generates docker-compose.override.yml.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DC_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OVERRIDE="$DC_DIR/docker-compose.override.yml"

HOME_DIR="${HOME:-${USERPROFILE:-}}"
if [ -z "$HOME_DIR" ]; then
    echo "Warning: Cannot determine home directory — auth forwarding may not work"
fi

# Create directories if they don't exist so Docker bind mounts succeed.
[ -n "$HOME_DIR" ] && mkdir -p "$HOME_DIR/.config/gh" "$HOME_DIR/.claude"

# ── Platform detection ───────────────────────────────────────────────
IS_WSL=false
if grep -qi "microsoft\|wsl" /proc/version 2>/dev/null; then
    IS_WSL=true
    echo "Platform: WSL"
elif [ "$(uname -s)" = "Linux" ]; then
    echo "Platform: native Linux"
else
    echo "Platform: $(uname -s)"
fi

# ── GPU detection ────────────────────────────────────────────────────
HAS_NVIDIA=false
HAS_DRI=false
HAS_DXG=false

# NVIDIA: check for nvidia-smi and nvidia-container-toolkit
if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi >/dev/null 2>&1; then
    if command -v nvidia-container-cli >/dev/null 2>&1 || \
       [ -f /usr/bin/nvidia-container-runtime ]; then
        HAS_NVIDIA=true
    else
        echo "GPU: NVIDIA GPU found but nvidia-container-toolkit not installed"
        echo "     Install it for GPU passthrough: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/"
        echo "     Ollama will run CPU-only until the toolkit is installed."
    fi
fi

# DRI render nodes (/dev/dri) — used by Intel, AMD, and sometimes NVIDIA
if [ -d /dev/dri ] && ls /dev/dri/renderD* >/dev/null 2>&1; then
    HAS_DRI=true
fi

# WSL2 DirectX GPU passthrough
if [ "$IS_WSL" = true ] && [ -e /dev/dxg ]; then
    HAS_DXG=true
fi

# ── Generate docker-compose.override.yml ─────────────────────────────
{
    echo "# Auto-generated by init-host.sh — do not edit manually."

    if [ "$HAS_NVIDIA" = false ] && [ "$HAS_DRI" = false ] && [ "$HAS_DXG" = false ]; then
        echo "# No GPU detected — running CPU-only."
        echo "services:"
        echo "  app: {}"
    else
        echo "# Detected: nvidia=$HAS_NVIDIA dri=$HAS_DRI wsl_dxg=$HAS_DXG"
        echo "services:"
        echo "  app:"

        # Collect devices
        DEVICES=()
        GROUP_ADD=()

        if [ "$HAS_DRI" = true ]; then
            DEVICES+=("/dev/dri:/dev/dri")
            GROUP_ADD+=("video" "render")
        fi

        if [ "$HAS_DXG" = true ]; then
            DEVICES+=("/dev/dxg:/dev/dxg")
        fi

        # Device passthrough
        if [ ${#DEVICES[@]} -gt 0 ]; then
            echo "    devices:"
            for d in "${DEVICES[@]}"; do
                echo "      - $d"
            done
        fi

        # Group membership for DRI access
        if [ ${#GROUP_ADD[@]} -gt 0 ]; then
            echo "    group_add:"
            for g in "${GROUP_ADD[@]}"; do
                echo "      - $g"
            done
        fi

        # WSL2 driver libs
        if [ "$IS_WSL" = true ] && [ -d /usr/lib/wsl/lib ]; then
            echo "    volumes:"
            echo "      - /usr/lib/wsl:/usr/lib/wsl:ro"
        fi

        # NVIDIA container toolkit (uses deploy.resources for compose v2)
        if [ "$HAS_NVIDIA" = true ]; then
            echo "    deploy:"
            echo "      resources:"
            echo "        reservations:"
            echo "          devices:"
            echo "            - driver: nvidia"
            echo "              count: all"
            echo "              capabilities: [gpu]"
        fi
    fi
} > "$OVERRIDE"

# Print summary
echo "GPU: $(head -2 "$OVERRIDE" | tail -1 | sed 's/^# //')"
echo "Host init complete."
